### PR TITLE
Add Dockerfile to run yarrrml-parser

### PR DESCRIPTION
**Pull request by vemonet**
Added:
* Dockerfile to run yarrrml-parser using `docker run`, using `node:12-alpine` as base
* Short instructions to build the Docker image and `docker run` in the readme
* `v1.1.0` and latest development build can be pulled from DockerHub at https://hub.docker.com/repository/docker/umids/yarrrml-parser

```bash
docker run --rm -it -v $(pwd)/resources:/app umids/yarrrml-parser:latest -i /app/test.yarrr.yml
```

### CODE REVIEW

**Comment by pheyvaer** [comment]
Hi @vemonet 

Thanks for the PR! We will have a look at it.

**Comment by vemonet** [comment]
Thanks for this parser! It was really straightforward to containerized and the `docker run` is quite fast on my Ubuntu

That allows me to avoid installing the package and use it in workflows combined either with RMLMapper or RMLStreamer

**Comment by pheyvaer** [comment]
Hi @vemonet 

I had a look.

- I tested it and works on my side :smile: 
- Is it possible to use the code of the repo in the Dockerfile instead of the version of npm?
- We are in the process of setting up a RML.io organization on Dockerhub, so it would be nice if we could actually host it there. Would that be fine for you too?

**Comment by vemonet** [comment]
Hi @pheyvaer ,

> Is it possible to use the code of the repo in the Dockerfile instead of the version of npm?

Just changed it in the Dockerfile and commited it. I also added a `.dockerignore` to avoid adding `node_modules` when doing `docker build`

> We are in the process of setting up a RML.io organization on Dockerhub, so it would be nice if we could actually host it there. Would that be fine for you too?

Yes, please! I would prefer to use an image maintained by your organization than my own image

**Comment by pheyvaer** [comment]
@vemonet Just wanna check in to see if you will make the changes or should I do them? :smile:

**Pull request merged**
